# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM oven/bun:latest

WORKDIR /app

# Copy package files and lockfile
COPY package.json bun.lock* ./

# Install dependencies using Bun
RUN bun install

# Copy the rest of the application
COPY . .

# Build the project
RUN bun run build

# Expose any required port if applicable (MCP servers typically use stdio, so not needed)

# Start the MCP server
CMD ["bun", "run", "dist/run.js"]
